SET DEFINE OFF;
Insert into HR.ACCOUNTINFORMATION
   (TYPE_ID, TYPE_NAME)
 Values
   (1, 'Saving');
Insert into HR.ACCOUNTINFORMATION
   (TYPE_ID, TYPE_NAME)
 Values
   (2, 'Current');
Insert into HR.ACCOUNTINFORMATION
   (TYPE_ID, TYPE_NAME)
 Values
   (3, 'NRE');
Insert into HR.ACCOUNTINFORMATION
   (TYPE_ID, TYPE_NAME)
 Values
   (4, 'NRO');
Insert into HR.ACCOUNTINFORMATION
   (TYPE_ID, TYPE_NAME)
 Values
   (5, 'RFC');
COMMIT;
