SET DEFINE OFF;
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (1, 'CHASE', '100 A rd.', '111-111-1111');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (2, 'Bank of America', '200 B rd.', '222-222-2222');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (3, 'CITI Bank', '300 C rd.', '333-333-3333');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (4, 'Bank of Texas', '400 D rd.', '444-444-4444');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (5, 'Center Bank', '500 E rd.', '555-555-5555');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (6, 'Capital One', '600 F rd.', '666-666-6666');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (7, 'ViewPoint Bank', '700 G rd.', '777-777-7777');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (8, 'Wells Fargo', '800 H rd.', '888-888-8888');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (9, 'TD Bank', '900 I rd.', '999-999-9999');
Insert into HR.BANKINFORMATION
   (ID, NAME, ADDRESS, PHONE)
 Values
   (10, 'HSBC Bank', '1000 J rd.', '101-010-1010');
COMMIT;
