SET DEFINE OFF;
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (1, 'David', 'Jones', 'DJ', 'aaa', 
    'davidjones@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (2, 'Kevin', 'James', 'KJ', 'bbb', 
    'kevinjames@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (3, 'Kevin', 'Love', 'KL', 'ccc', 
    'kevinlove@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (4, 'Derek', 'Fisher', 'DF', 'ddd', 
    'derekfisher@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (5, 'James', 'Harden', 'JH', 'eee', 
    'jamesharden@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (6, 'Dwight', 'Howard', 'DH', 'fff', 
    'dwighthoward@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (7, 'Tim', 'Duncan', 'TD', 'ggg', 
    'timduncan@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (8, 'Dirk', 'Nowitzki', 'DN', 'hhh', 
    'dirkdowitzki@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (9, 'Vince', 'Carter', 'VC', 'iii', 
    'vincecareter@gmail.com');
Insert into HR.CUSTOMERINFORMATION
   (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, 
    EMAIL)
 Values
   (10, 'Blake', 'Griffin', 'BG', 'jjj', 
    'blakegriffin@gmail.com');
COMMIT;
